# $ docker run -dit --name my-apache-app -p 8080:80 -v "$PWD":/usr/local/apache2/htdocs/ httpd:2.4
version: '3.2'

services:
  web:
    image: "httpd:2.4"
    container_name: apache-webWorkerPoc

    volumes:
    - type: bind
      source: ./
      target: /usr/local/apache2/htdocs/

    ports:
      - "8888:80"